---
# code: language=ansible
# default file for trng_env role
trng_env_trainees_count: 3
trng_env_training_image: "podman-training:latest"
trng_env_image_build_path: "/opt/training-image"
trng_env_image_container_name: "podman-training-container"
trng_env_image_base_image: "ubuntu:24.04"
trng_env_trainee_container_state: "started"  # absent present stopped started created quadlet
trng_env_cleanup: false
trng_env_image_apt_packages:
  - bash-completion
  - ca-certificates
  - curl
  - fuse-overlayfs
  - git
  - iproute2
  - iputils-ping
  - jq
  - less
  - nano
  - net-tools
  - openssh-client
  - openssh-server
  - openssl
  - podman
  - podman-docker
  - podman-compose
  - python3
  - python3-pip
  - python3-venv
  - rsync
  - slirp4netns
  - sudo
  - tmux
  - uidmap
  - vim
  - wget
